- name: Cowsay
  hosts: webservers
  become: yes
  tasks:
    - name: Install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: present
      tags:
        - install_nginx
      when: ansible_distribution == "Ubuntu"

    - name: run cowsay
      ansible.builtin.command: "/usr/games/cowsay {{ server_message }}"
      register: cowsay_result
      when: ansible_distribution == "Ubuntu"

    - name: debug
      debug:
        msg: "{{cowsay_result['stdout_lines']| join('\n')}}"
      when: ansible_distribution == "Ubuntu"


- name: Setup nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      tags:
        - install_nginx
      when: ansible_distribution == "Ubuntu"

    - name: Add index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ root_dir }}/index.html"
      when: ansible_distribution == "Ubuntu"


    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      tags:
        - configure_nginx
      when: ansible_distribution == "Ubuntu"

  handlers:
  - name: restart nginx
    become: yes
    ansible.builtin.service:
      name: nginx
      state: reloaded
