- name: Setup nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      tags:
        - install_nginx

    - name: Add index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ root_dir }}/index.html"

    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      tags:
        - configure_nginx

  handlers:
  - name: restart nginx
    become: yes
    ansible.builtin.service:
      name: nginx
      state: reloaded
