- name: Remove git
  hosts: webservers
  become: yes
  gather_facts: no
  tasks:
    - name: Remove git
      ansible.builtin.apt:
        name: git
        state: absent
      tags:
        - git

    - name: remove Gitconfig for users
      ansible.builtin.file:
        path: "/home/{{ item }}/.gitconfig"
        state: absent
      loop: "{{ users }}"
