- name: Remove git
  hosts: webservers
  become: yes
  tasks:
    - name: Remove git
      ansible.builtin.apt:
        name: git
        state: absent
      tags:
        - git
      when: ansible_distribution == "Ubuntu"

    - name: remove Gitconfig for users
      ansible.builtin.file:
        path: "/home/{{ item }}/.gitconfig"
        state: absent
      loop: "{{ users }}"
      when: ansible_distribution == "Ubuntu"
