- name: Setup Git
  hosts: webservers
  become: yes
  tasks:
    - name: Update Apt cache
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - apt_cache
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: latest
        update_cache: yes
      tags:
        - git
