- name: Setup server configuration
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.postgresql
      postgresql_hba_entries:
        - { type: local, database: all, user: postgres, auth_method: trust }

    - role: geerlingguy.nodejs
      nodejs_version: "14.x"
